
defaults:
  - processor: dataloader

_target_: synth.processors.processor

params:
  path2load_data:
    - /home/shlomis/PycharmProjects/commercial_synth_dataset/audio_output/
  path2load_labels:
    - /home/shlomis/PycharmProjects/commercial_synth_dataset/full_parameters.csv
  batch_size:
    - 512
  num2mask:
    - 10
  t_axis_size:
    - 138
  shuffle:
    - True