# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
      - /home/moshelaufer/PycharmProjects/datasets/noy_synth/
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  path2load_model: #/home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy/

  model:
    _target_: Projects_torch.model.ViT.MyViT
    chw:
      - 256
      - 128
      - 256
    n_patches: 7
    n_blocks: 6
    hidden_d: 512
    n_heads: 8
    out_d: 104
    input_d: 128


  outputs_dimension_per_outputs:
    - 3
    - 12
    - 20
    - 31
    - 4
    - 5
    - 8
    - 5
    - 16

#    transformer:
#      _target_: Projects_torch.layers.transformer_encoder.TransformerE
#      d_model: 512
#      num_heads: 8
#      num_layers: 6
#      d_ff: 768 #2048
#      max_seq_length: 257 #65 #129 #65 # 128
#      dropout: 0.1
#      top_k: 5

  loss:
    - _target_: Projects_torch.losses.l2_loss.L2Loss

  loss_ce:
    _target_: Projects_torch.losses.cross_entropy_loss_2.CELoss
    num_classes: 1
    index_y_true: 1
    outputs_dimension_per_outputs:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16
  num_ce_loss: 1

  loss_l2: False

  to_schedule: True

  schedule:
    _target_: callbacks.WarmLRSchedule
    initial_learning_rate: 6e-6
    warmup_steps: 8
    hold_step: 1000 #1
    decay_step: 10
    max_learn_rate: 7.5e-5
    min_learn_rate: 1.5e-6

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 1e-4

  processor:
    _target_: Projects_torch.processors.processor_synth_encoder_eml_spec.DataLoaderMelSpec
    autoencoder: False
    encoder: True
    num_classes:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16

    win_length: 256
    n_fft: 1025

  batch_size:
    train: 100 # 240 #118 #48
    test: 1
    valid: 100 #118 #48

  learning_rate: 3e-3 #0.5e-7

  epochs: 4000
  path2save_model: C:\Users\moshe\PycharmProjects\checkpoints\noy_encoder #/home/moshela/work/moshe/pycharm/checkpoints/noy/checkpoint_4.pt #    /home/moshelaufer/PycharmProjects/results/models/
  model_name: synth_vit_stft_noy
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_autoencoder_2_stft/
  num_outputs: 2 #10 #1
  path2save_plot_model: /home/moshelaufer/PycharmProjects/results/plot/model_plot_tal_noise.png

  steps_per_epoch: 10 # 2500
  validation_steps: 150

  results:
    _target_: Projects_torch.results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/results
    num_class: 100

