
_target_: synth.models.self_supervised_model

params:

  kernel_size:
    - 10
    - 5
    - 3
    - 3
    - 2
    - 2
    - 2

  stride_size:
    - 5
    - 3
    - 2
    - 2
    - 1
    - 1
    - 1

  in_channels:
    - 1
  out_channels:
    - 512
  word_depth:
    - 512
  G:
    - 2
  V:
    - 320
  tau:
    - 2.

  num_layers:
    - 24
  d_model:
    - 512
  num_heads:
    - 8
  dff:
    - 4096

  activation:
    - 'gelu'