from losses.l2_loss import L2Loss
from losses.smooth_l1_loss import SmoothL1Loss
from losses.l2_regression import L2LossReg
from losses.cross_entropy_loss import CELoss
from losses.cross_entropy_loss_2 import CELoss
from losses.spectral_magnitude_losses import Spectral_LogSTFTMagnitude_Loss
from losses.loss_instantiate_util import losses_instantiate
