# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load: /home/moshelaufer/PycharmProjects/datasets/tal_noise_1
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  input_shape:
    -
      -
      - 16384


  model:
    _target_: model.synth_encoder_model.SynthEncoder

    inputs:
      - 16384
      - 1

    conv_encoder:
      _target_: layers.conv_wav_encoder.ConvFeatureExtractionModel
      activation: relu
      units: 512
      conv_layers:
        -
          - 512
          - 10 #6
          - 5 #3

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 2
          - 2 #1

        -
          - 512
          - 2
          - 2 #1

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1

      dropout: 0.1
      conv_bias: True
#      mode: none


    conv_decoder:
      _target_: layers.conv_wav_decoder.ConvDecoderModel
      activation: relu
      units: 1
      conv_layers:
        -
          - 512
          - 2
          - 2
          - 1

        -
          - 512
          - 2
          - 2
          - 1

        -
          - 512
          - 3
          - 2
          - 1

        -
          - 512
          - 3
          - 2
          - 1

        -
          - 512
          - 3
          - 2
          - 0

        -
          - 512
          - 3
          - 2
          - 0

        -
          - 512
          - 10
          - 5
          - 4

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1

      dropout: 0.1
      conv_bias: True

    top_k_transformer: 6

    transformer_encoder:
      _target_: layers.transformer_encoder.EncoderTransformer
      num_layers: 6
      d_model: 512
      num_attention_heads: 12
      dff: 768
      dropout_rate: 0.1
      dim_conv: 1
      activation: gelu

    transformer_decoder:
      _target_: layers.transformer_decoder.DecoderTransformer
      num_layers: 6
      d_model: 512
      num_attention_heads: 12
      dff: 768
      dropout_rate: 0.1
      dim_conv: 1
      activation: gelu

    params_predictor:
      _target_: layers.params_predictor.ParamsPredictor

  loss:
    - _target_: losses.l2_regression.L2LossReg
#    - _target_: losses.soft_dtw_loss.SoftDTWLoss
#      gamma: 1.
    - _target_: losses.l2_loss.L2Loss
    - _target_: losses.l2_loss.L2Loss
#    - _target_: losses.soft_dtw_loss.SoftDTWLoss
#      gamma: 1.

  callbacks:
    -
      _target_: tensorflow.keras.callbacks.ModelCheckpoint
      filepath: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_encoder/
      save_weights_only: False
      save_best_only: True
      save_freq: 'epoch'
      initial_value_threshold: 1
      monitor: 'loss'
      verbose: 1

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.000005
    beta_1: 0.9
    beta_2: 0.99

  processor:
    _target_: processors.processor_synth_encoder.Processor
    num_classes:
      - 16
      - 16
      - 8
      - 8
      - 9
      - 8
      - 9
      - 9
      - 2
      - 4
      - 4
      - 4
      - 17
      - 17
      - 17
      - 17

#    path2sets: /home/moshelaufer/PycharmProjects/datasets/tal_noise_25000_labels/list_of_set_labels.pkl


  batch_size:
    train: 64
    test: 1
    valid: 64

  epochs: 120
  path2save_model: /home/moshelaufer/PycharmProjects/results/models
  model_name: synth_encoder
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_encoder/1/
  num_outputs: 16

  results:
    _target_: results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/results
    num_class: 100

