
optimizer:
  _target_: optimizers.multi_optimizer.Optimizers
  indexes:
    - 1 # encoder
    - 4 # transformer
    - 5 # decoder
    - 7 # linear

  ind_transformer_layer: 4

  optimizers_list:
    # encoder
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 0.988e-6
          min_learn_rate: 3e-8

  # transformer
    # 0
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.098e-6
          min_learn_rate: 3e-8

    # 1
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.22e-6
          min_learn_rate: 3e-8

    # 2
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.35e-6
          min_learn_rate: 3e-8

    # 3
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.5e-6
          min_learn_rate: 3e-8

    # 4
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.67e-6
          min_learn_rate: 3e-8

    # 5
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 1.86e-6
          min_learn_rate: 3e-8

    # 6
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 2.0667e-6
          min_learn_rate: 3e-8

    # 7
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 2.296e-6
          min_learn_rate: 3e-8

    # 8
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 2.55e-6
          min_learn_rate: 3e-8

    # 9
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 2.83e-6
          min_learn_rate: 3e-8

    # 10
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 3.15e-6
          min_learn_rate: 3e-8

    # 11
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 3.5e-6
          min_learn_rate: 3e-8

    # decoder
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 0.988e-6
          min_learn_rate: 3e-8

    # linear
    - _target_: tensorflow.keras.optimizers.Adam
      learning_rate:
#        _target_: tensorflow.keras.callbacks.LearningRateScheduler
#        schedule:
          _target_: callbacks.WarmLRSchedule
          initial_learning_rate: 1e-7
          warmup_steps: 25
          hold_step: 1
          decay_step: 30
          max_learn_rate: 3.6e-6
          min_learn_rate: 3e-8
