# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
      - /home/moshelaufer/PycharmProjects/datasets/tal_noise_shlomi/
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  input_shape:
    -
      -
      - 16384
    -
      -
      - 50

  model:
    _target_: model.ssl_synth_model.SSLSynthModel

    inputs1:
      - 16384
      - 1

    inputs2:
      - 50

    conv_encoder:
      _target_: layers.conv_wav_encoder.ConvFeatureExtractionModel
      activation: gelu
      units: 512
      conv_layers:
        -
          - 512
          - 10
          - 5

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 3
          - 2

        -
          - 512
          - 2
          - 2

        -
          - 512
          - 2
          - 2

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1

      dropout: 0.1
      conv_bias: True
      is_group_norm: True
      is_layer_norm: False

    transformer_encoder_s:
      _target_: layers.transformer_encoder.EncoderTransformer
      num_layers: 12
      d_model: 512
      num_attention_heads: 8
      dff: 768
      dropout_rate: 0.1
      dim_conv: 1
      activation: gelu

      transformer_encoder_t:
        _target_: layers.transformer_encoder.EncoderTransformer
        num_layers: 12
        d_model: 512
        num_attention_heads: 8
        dff: 768
        dropout_rate: 0.1
        dim_conv: 1
        activation: gelu

  loss:
    _target_: losses.l2_loss.L2Loss

  callbacks:
    -
      _target_: tensorflow.keras.callbacks.ModelCheckpoint
      filepath: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_encoder/1/
      save_weights_only: False
      save_best_only: True
      save_freq: 'epoch'
      initial_value_threshold: 1
      monitor: 'loss'
      verbose: 1

    -
      _target_: tensorflow.keras.callbacks.LearningRateScheduler
      schedule:
        _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
        initial_learning_rate: 1e-4
        decay_steps: 600
        decay_rate: 2e-4

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.000001
    beta_1: 0.9
    beta_2: 0.99

  processor:
    _target_: processors.processor_wav_files.Processor
    t_axis: 50
    prob2mask: 0.13
    masking_size: 2
    load_label: False

  batch_size:
    train: 128
    test: 1
    valid: 128

  epochs: 5000
  path2save_model: /home/moshelaufer/PycharmProjects/results/models
  model_name: synth_encoder
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_encoder/
  num_outputs: 1

  steps_per_epoch: 500
  validation_steps: 50

  results:
    _target_: results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/results
    num_class: 100

