# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
      - /home/moshelaufer/PycharmProjects/datasets/noy_synth/
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  path2load_model: #/home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy/

  path2save_images: C:\Users\moshe\PycharmProjects\results\images

  model:
    _target_: Projects_torch.model.synth_transformer_decoder.SynthTransformerDecoder
    transformer:
      _target_: Projects_torch.layers.transformer_decoder.TransformerD
      d_model: 512
      num_heads: 16
      num_layers: 12
      d_ff: 2048
      input_shape:
        - 128
        - 1025
      dropout: 0.1
      path2csv: 'C:\Users\moshe\PycharmProjects\commercial_synth_dataset\noy\Data_custom_synth.csv'

  to_metrics: False #

#    num_classes: 1
#    index_y_true: 1

  loss_ce:

  loss:
#    - _target_: losses.spectral_magnitude_losses.Spectral_LogSTFTMagnitude_Loss
    - _target_: Projects_torch.losses.l2_loss.L2Loss

  loss_l2: True

  callbacks:
    -
      _target_: tensorflow.keras.callbacks.ModelCheckpoint
      filepath: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy/8/
      save_best_only: True
      save_freq: 7500 #'epoch'
      initial_value_threshold: 5
      monitor: 'linear_classifier_loss'
      verbose: 1

  to_schedule: True

  schedule:
    _target_: callbacks.WarmLRSchedule
    initial_learning_rate: 6e-6
    warmup_steps: 8
    hold_step: 1000 #1
    decay_step: 10
    max_learn_rate: 7.5e-5 #2.5e-5 #8e-6 #1.5e-6
    min_learn_rate: 1.5e-6 #9e-7

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 1e-4 #1.6e-6 #1.25e-6

  processor:
    _target_: Projects_torch.processors.processor_synth_decoder_stft.DataLoaderSTFT
    norm_mean: 0.013329904
    norm_std: 0.041720923

    num_classes:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16

  batch_size:
    train: 80 #48
    test: 1
    valid: 80 #48

  learning_rate: 8e-4 #0.5e-7

  epochs: 4000
  path2save_model: C:\Users\moshe\PycharmProjects\checkpoints\noy_decoder #/home/moshela/work/moshe/pycharm/checkpoints/noy/decoder
  model_name: synth_decoder_stft_noy
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_decoder_stft/
  num_outputs: 1
  path2save_plot_model: /home/moshelaufer/PycharmProjects/results/plot/model_plot_tal_noise.png

  steps_per_epoch: 1000
  validation_steps: 150

