# @package _group_
data2vecmodel:
  _target_: model.data2vec_model.Data2VecModel
  conv_encoder:
    _target_: layers.conv_feature_encoder.ConvFeatureExtractionModel
    conv_layers: [(512, 10, 5), (512, 5, 3), (512, 3, 2)]
    dropout: 0.0
    mode: default
    conv_bias: False
  transformer_encoder:
    _target_: layers.


#optimizer:
#  _target_: draft.Optimizer
#  optim:
#    _target_: draft.Optim
#    algo_rec: SGD_rec
#    lr_rec: 0.01111
#  algo: SGD
  lr: 0.01



#params:

#  kernel_size:
#    - 10
#    - 5
#    - 3
#    - 3
#    - 2
#    - 2
#    - 2
#
#  stride_size:
#    - 5
#    - 3
#    - 2
#    - 2
#    - 1
#    - 1
#    - 1
#
#  in_channels:
#    - 1
#  out_channels:
#    - 512
#  word_depth:
#    - 512
#  G:
#    - 2
#  V:
#    - 320
#  tau:
#    - 2.
#
#  num_layers:
#    - 24
#  d_model:
#    - 512
#  num_heads:
#    - 8
#  dff:
#    - 4096
#
#  activation:
#    - 'gelu'
#    -

#name: resnet
#num_layers: 50 # As 50 is the default value
#
