# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
      - /home/moshelaufer/PycharmProjects/datasets/noy_synth/
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  path2load_model:

  model:
    _target_: Projects_torch.model.ViT_pretrain.ViTPretrain
    chw:
      - 256
      - 128
      - 256
    n_patches: 7
    n_blocks: 6
    hidden_d: 1024
    n_heads: 8
    out_d: 104
    input_d: 128

  outputs_dimension_per_outputs:
    - 3
    - 12
    - 20
    - 31
    - 4
    - 5
    - 8
    - 5
    - 16

  loss:
    - _target_: Projects_torch.losses.l2_loss.L2Loss

  loss_ce:
    _target_: Projects_torch.losses.cross_entropy_loss_2.CELoss
    num_classes: 1
    index_y_true: 1
    outputs_dimension_per_outputs:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16
  num_ce_loss: 1

  loss_l2: False

  to_schedule: True

  schedule:
    _target_: callbacks.WarmLRSchedule
    initial_learning_rate: 6e-6
    warmup_steps: 8
    hold_step: 1000 #1
    decay_step: 10
    max_learn_rate: 7.5e-5
    min_learn_rate: 1.5e-6

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 1e-4

  processor:
    _target_: Projects_torch.processors.processor_synth_encoder_eml_spec.DataLoaderMelSpec
    encoder: True
    num_classes:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16

    win_length: 256
    n_fft: 1025

  batch_size:
    train: 32
    test: 1
    valid: 32

  num_workers:
    train: 3
    valid: 1

  learning_rate: 1e-4 #0.5e-7

  epochs: 4000
  model_name: synth_vit_stft_noy
  num_outputs: 2

  steps_per_epoch: 10
  validation_steps: 150


