# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
#      - /home/moshelaufer/PycharmProjects/datasets/tal_noise_2/
      - /home/moshela/work/moshe/pycharm/dataset/tal
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  saved_model:  #/home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_shlomi/1/

  model:
    _target_: Projects_tensorflow.model.synth_autoencoder_model_2_stft_v2.SynthAutoEncoder

    inputs1:
      - 130 #33
      - 129 #40

    inputs2:
      - 65 #33
      - 1

    conv_encoder:
      _target_: Projects_tensorflow.layers.conv_wav_encoder.ConvFeatureExtractionModel
      activation: gelu
      units: 512
      conv_layers:
        -
          - 512
          - 4
          - 2

        -
          - 512
          - 3
          - 1

        -
          - 512
          - 3
          - 1

        -
          - 512
          - 2
          - 1

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1

      dropout: 0.1
      conv_bias: True
      is_group_norm: True
      is_layer_norm: False

    transformer:
      _target_: Projects_tensorflow.layers.transformer.Transformer
      num_transformer_blocks: 12
      d_model: 512
      num_heads: 12
      d_ff: 3072
      dropout: 0.1
      activation: gelu
      decoder: False

    linear_classifier:
      _target_: Projects_tensorflow.layers.linear_classifier_2.LinearClassifier
      activation: relu
      dropout: 0.2
      outputs_dimension_per_outputs:
        - 16
        - 4
        - 9
        - 4
        - 17
        - 17
        - 4
        - 17
        - 17

  to_metrics: False

  metrics:
    _target_: Projects_tensorflow.metrics.accuracy_2.CustomAccuracy2
    outputs_dimension_per_outputs:
      - 16
      - 4
      - 9
      - 4
      - 17
      - 17
      - 4
      - 17
      - 17

#  loss:
#    - _target_: Projects_tensorflow.losses.l2_loss.L2Loss

  loss_ce:
    _target_: Projects_tensorflow.losses.cross_entropy_loss_2.CELoss
    num_classes: 1
    index_y_true: 1
    outputs_dimension_per_outputs:
      - 16
      - 4
      - 9
      - 4
      - 17
      - 17
      - 4
      - 17
      - 17

  num_ce_loss: 1

  callbacks:
    -
      _target_: tensorflow.keras.callbacks.ModelCheckpoint
      filepath: /home/moshela/work/moshe/pycharm/checkpoints/tal
      save_best_only: True
      save_freq: 2000 #'epoch'
      initial_value_threshold: 20
      monitor: 'loss'
      verbose: 1
#    -
#      _target_: tensorflow.keras.callbacks.LearningRateScheduler
#      verbose: 1
#      schedule:
#        _target_: callbacks.scheduler
#        epoch: 0
#        lr: 1e-7

#    -
#      _target_: tensorflow.keras.callbacks.LearningRateScheduler
#      schedule:
#        _target_: callbacks.WarmLRSchedule
#        initial_learning_rate: 0.5e-6
#        warmup_steps: 25
#        hold_step: 1
#        decay_step: 200
#        max_learn_rate: 1.8e-6
#        min_learn_rate: 3e-8
#
#        _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
#        initial_learning_rate: 8.5e-5
#        decay_steps: 750
#        decay_rate: 1e-4

  to_schedule: True

  schedule:
    _target_: Projects_tensorflow.callbacks.WarmLRSchedule
    initial_learning_rate: 6e-6
    warmup_steps: 8
    hold_step: 70 #1
    decay_step: 10
    max_learn_rate: 7.5e-5 #2.5e-5 #8e-6 #1.5e-6
    min_learn_rate: 0.1e-6 #1.5e-6 #5e-7


  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 8e-6 #1.25e-6

  processor:
    _target_: Projects_tensorflow.processors.processor_synth_encoder_mask_2_stft.Processor #processors.processor_synth_encoder.Processor #
    norm_mean: 0.083749466
    norm_std: 0.4324925
    std_mean_calc:
      _target_: dataset.calc_std_mean_dataset_wav.StdMeanCalc
      path2dataset: /home/moshela/work/moshe/pycharm/dataset/tal #/home/moshelaufer/PycharmProjects/datasets/tal_noise/
      stft: True
    mask:
      - 65 #33
      - 1
    num_classes:
      - 16
      - 4
      - 9
      - 4
      - 17
      - 17
      - 4
      - 17
      - 17

  batch_size:
    train: 57 #57 #48
    test: 1
    valid: 57 #57 #48

  epochs: 4000
  path2save_model: /home/moshela/work/moshe/pycharm/saved_models
# /home/moshelaufer/PycharmProjects/results/models/
  model_name: synth_autoencoder_2_stft_tal_shlomi_v2
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_autoencoder_2_stft_shlomi/
  num_outputs: 1 #10 #1
  path2save_plot_model: /home/moshela/work/moshe/pycharm/saved_models/model_plot_tal_v2.png

  steps_per_epoch: 1000 # 2500
  validation_steps: 150

  results:
    _target_: Projects_tensorflow.results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/results
    num_class: 100

