# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load: C:\Users\moshe\PycharmProjects\datasets\dx_wav
    type_files: wav
    labels: False
    dataset_names: dx_wav

  input_shape:
    -
      -
      - 16384
    -
      -
      - 50

  model:
    _target_: model.data2vec_wav_model.Data2VecModel

    len_latent_space: 50
    tau: 0.9

    inputs1:
      - 16384
      - 1

    inputs2:
      - 50

    conv_encoder:
      _target_: layers.conv_wav_encoder.ConvFeatureExtractionModel
      activation: gelu
      units: 512
      conv_layers:
        -
          - 512
          - 10
          - 5

        -
          - 512
          - 3
          - 2
        -
          - 512
          - 3
          - 2
        -
          - 512
          - 3
          - 2
        -
          - 512
          - 3
          - 2
        -
          - 512
          - 2
          - 2
        -
          - 512
          - 2
          - 2

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1

      dropout: 0.0
      conv_bias: True

    masking: True
    masking_layer:
      _target_: layers.masking.Masking
      num_channels: 512

    ffn:
      _target_: layers.ffn.FFN
      dff: 512
      activation: gelu
      num_layers: 2

    top_k_transformer: 8

    transformer_encoder:
      _target_: layers.transformer_encoder.TransformerEncoder
      num_layers: 12
      d_model: 512
      num_attention_heads: 8
      dff: 768
      dropout_rate: 0.1
      dim_conv: 1

  loss:
    _target_: losses.l2_loss.L2Loss #tf.keras.losses.MeanSquaredError

  callbacks:
#    -
#      _target_: callbacks.callbacks.EMACallback
#      t_n: 30000
#      t_0: 0.999
#      t_e: 0.9999
    -
      _target_: callbacks.callbacks.LearnRateSchedulerTriStage
      initial_lr: 0.0001
      peak: 0.00005
      steps2warp_up: 0.03
      steps2hold: 0.67
      decay: 0.3
      train_steps_per_epoch: 10
      epochs: 15

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.0005
    beta_1: 0.9
    beta_2: 0.99

  train_steps_per_epoch: 350

  processor:
    _target_: processors.processor_wav_files.Processor
    t_axis: 50
    prob2mask: 0.065 #0.4
    masking_size: 10 #5
    load_label: False

  batch_size:
    train: 16
    test: 16
    valid: 16

  epochs: 15
  path2save_model: C:\Users\moshe\PycharmProjects\save_models\models
  model_name: data2vec

  results:
    _target_: results.results.Results
    path2save_results: C:\Users\moshe\PycharmProjects\save_models\results
    num_class: 100

