# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load:
#      - /home/moshelaufer/PycharmProjects/datasets/noy_synth/
      - /home/moshela/work/moshe/pycharm/dataset/noy
    type_files: wav
    labels: True
    dataset_names: tal_noise_1

  saved_model: #/home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy/8/

  model:
    _target_: Projects_tensorflow.model.synth_autoencoder_model_2_stft_v2.SynthAutoEncoder

    inputs1:
      - 130 #33 #129
      - 129 #40 #512

    inputs2:
      - 65 #33 #129
      - 65 #1

    conv_encoder:
      _target_: Projects_tensorflow.layers.conv_wav_encoder.ConvFeatureExtractionModel
      activation: gelu
      units: 512
      conv_layers:
        -
          - 512
          - 4
          - 2

        -
          - 512
          - 3
          - 1

        -
          - 512
          - 3
          - 1

        -
          - 512
          - 2
          - 1

      num_duplicate_layer:
        - 1
        - 1
        - 1
        - 1

      dropout: 0.1
      conv_bias: True
      is_group_norm: True
      is_layer_norm: False

    transformer:
      _target_: Projects_tensorflow.layers.transformer.Transformer
      num_transformer_blocks: 12
      d_model: 512
      num_heads: 12
      d_ff: 3072
      dropout: 0.1
      activation: gelu
      decoder: False


    linear_classifier:
      _target_: Projects_tensorflow.layers.linear_classifier_2.LinearClassifier
      activation: relu
      dropout: 0.2
      outputs_dimension_per_outputs:
        - 3
        - 12
        - 20
        - 31
        - 4
        - 5
        - 8
        - 5
        - 16

  to_metrics: False #

  metrics:
    _target_: Projects_tensorflow.metrics.accuracy_2.CustomAccuracy2
    outputs_dimension_per_outputs:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16
#    num_classes: 1
#    index_y_true: 1

#  loss:
#    - _target_: Projects_tensorflow.losses.l2_loss.L2Loss

  loss_ce:
    _target_: Projects_tensorflow.losses.cross_entropy_loss_2.CELoss
    num_classes: 1
    index_y_true: 1
    outputs_dimension_per_outputs:
        - 3
        - 12
        - 20
        - 31
        - 4
        - 5
        - 8
        - 5
        - 16
  num_ce_loss: 1

  callbacks:
    -
      _target_: tensorflow.keras.callbacks.ModelCheckpoint
      filepath: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy_v2/1/
      save_best_only: True
      save_freq: 2000 #'epoch'
      initial_value_threshold: 5
      monitor: 'loss'
      verbose: 1

#    -
#      _target_: tensorflow.keras.callbacks.LearningRateScheduler
#      schedule:
#        _target_: callbacks.WarmLRSchedule
#        initial_learning_rate: 0.5e-7
#        warmup_steps: 25
#        hold_step: 1
#        decay_step: 100
#        max_learn_rate: 1.5e-6
#        min_learn_rate: 3e-8
#    -
#      _target_: tensorflow.keras.callbacks.LearningRateScheduler
#      schedule:
#        _target_: tensorflow.keras.optimizers.schedules.ExponentialDecay
#        initial_learning_rate: 8.5e-5
#        decay_steps: 750
#        decay_rate: 1e-4

  to_schedule: True

  schedule:
    _target_: Projects_tensorflow.callbacks.WarmLRSchedule
    initial_learning_rate: 6e-6
    warmup_steps: 8
    hold_step: 130 #1
    decay_step: 10
    max_learn_rate: 7.5e-5 #2.5e-5 #8e-6 #1.5e-6
    min_learn_rate: 0.4e-6 #9e-7

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 1.6e-6 #1.25e-6
#      _target_: tensorflow.keras.callbacks.LearningRateScheduler
#      schedule:
#      _target_: callbacks.WarmLRSchedule
#      initial_learning_rate: 0.5e-7
#      warmup_steps: 25
#      hold_step: 1
#      decay_step: 100
#      max_learn_rate: 1.5e-6
#      min_learn_rate: 3e-8

  processor:
    _target_: Projects_tensorflow.processors.processor_synth_encoder_mask_2_stft.Processor #processors.processor_synth_encoder.Processor #
    norm_mean: 0.013329904
    norm_std: 0.041720923
    std_mean_calc:
      _target_: dataset.calc_std_mean_dataset_wav.StdMeanCalc
      path2dataset: /home/moshela/work/moshe/pycharm/dataset/noy #/home/moshelaufer/PycharmProjects/datasets/tal_noise/
      stft: True
    mask:
      - 65 #33 #129
      - 1
    num_classes:
      - 3
      - 12
      - 20
      - 31
      - 4
      - 5
      - 8
      - 5
      - 16

  batch_size:
    train: 140 #57 #
    test: 1
    valid: 140 #57 #

  epochs: 4000
  path2save_model: /home/moshelaufer/PycharmProjects/results/models/
  model_name: synth_autoencoder_2_stft_noy_v2
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv/synth_autoencoder_2_stft/
  num_outputs: 1
  path2save_plot_model: /home/moshelaufer/PycharmProjects/results/plot/model_plot_tal_noise_v2.png

  steps_per_epoch: 700 # 2500
  validation_steps: 75

  results:
    _target_: Projects_tensorflow.results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/results
    num_class: 100

