# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load: C:\Users\moshe\PycharmProjects\datasets\tal_noise
    type_files: wav
    labels: True
    dataset_names: dx_wav

  input_shape:
    -
      -
      - 16384
    -
      -
      - 50

  model:
    _target_: model.data2vec_wav_model_ft.Data2VecModelFT

    inputs:
      - 16384
      - 1

    top_k_transformer: 1

    path2load_model: C:\Users\moshe\PycharmProjects\save_models\models\26

  loss:
    _target_: losses.l2_regression.L2LossReg #tf.keras.losses.MeanSquaredError

  callbacks:
#    -
#      _target_: callbacks.callbacks.EMACallback
#      t_n: 30000
#      t_0: 0.999
#      t_e: 0.9999
    -
      _target_: callbacks.callbacks.LearnRateSchedulerTriStage
      initial_lr: 0.0001
      peak: 0.00005
      steps2warp_up: 0.03
      steps2hold: 0.67
      decay: 0.3
      train_steps_per_epoch: 10
      epochs: 15

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.99

  train_steps_per_epoch: 350

  processor:
    _target_: processors.processor_wav_files_ft.Processor

  batch_size:
    train: 16
    test: 1
    valid: 16

  epochs: 1
  path2save_model: C:\Users\moshe\PycharmProjects\save_models\models
  path2save_csv: C:\Users\moshe\PycharmProjects\save_models\results
  model_name: data2vec

  results:
    _target_: results.results.Results
    path2save_results: C:\Users\moshe\PycharmProjects\save_models\results
    num_class: 100

