# @package _group_

TrainTask:

  dataset_class:
    _target_: dataset.dataset.Dataset
    path2load: /home/moshelaufer/PycharmProjects/datasets/tal_noise_1
    type_files: wav
    labels: True
    dataset_names: dx_wav

  input_shape:
    -
      -
      - 16384
    -
      -
      - 509 #50

  model:
    _target_: model.data2vec_wav_model_ft.Data2VecModelFT

    inputs:
      - 16384
      - 1

    top_k_transformer: 1
    model_trainable: False

    path2load_model: /home/moshelaufer/PycharmProjects/results/checkpoint/data2vec_wav_1/

  loss:
    _target_: losses.l2_regression.L2LossReg #tf.keras.losses.MeanSquaredError

  callbacks:
#    -
#      _target_: callbacks.callbacks.EMACallback
#      t_n: 30000
#      t_0: 0.999
#      t_e: 0.9999
    -
      _target_: callbacks.callbacks.LearnRateSchedulerTriStage
      initial_lr: 0.0001
      peak: 0.00005
      end: 0.00005
      steps2warp_up: 0.03
      steps2hold: 0.67
      decay: 0.3
      train_steps_per_epoch: 1500
      epochs: 15

  optimizer:
    _target_: tensorflow.keras.optimizers.Adam
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.99

  train_steps_per_epoch: 350

  processor:
    _target_: processors.processor_wav_files_ft.Processor

  batch_size:
    train: 32
    test: 1
    valid: 32

  epochs: 20
  path2save_model: /home/moshelaufer/PycharmProjects/results/models/
  model_name: data2vec_wav_ft
  path2save_csv: /home/moshelaufer/PycharmProjects/results/csv

  results:
    _target_: results.results.Results
    path2save_results: /home/moshelaufer/PycharmProjects/results/results/
    num_class: 100

